### ISSUE TITLE
[BUG] SyntaxError: invalid character '·' (U+00B7)

### ISSUE THREAD

**Issue by x3vyx** [xob0t/qBittorrent-File-Matcher#1]
I'm getting this error and i dont know how to fix xD

PS C:\Users\x3vyx> python qbittorrent_file_matcher.py a9c06c5a025f6b5c91bac3ec963309232e215e04
  File "C:\Users\x3vyx\qbittorrent_file_matcher.py", line 95
    <title>qBittorrent-File-Matcher/qbittorrent_file_matcher.py at main · xob0t/qBittorrent-File-Matcher</title>
                                                                        ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by xob0t** [comment]
looks like you've downloaded html page instead of the script
open https://raw.githubusercontent.com/xob0t/qBittorrent-File-Matcher/main/qbittorrent_file_matcher.py
press Ctrl+S to save as file

**Comment by x3vyx** [comment]
Oh yeah, now works, sorry for the noobiness xd THank you !
