### ISSUE TITLE
[Feature Request] Auto Sync All Torrent 

### ISSUE THREAD

**Issue by x3vyx** [xob0t/qBittorrent-File-Matcher#2]
A way to sync all torrents active in qbittorrent with specific folder
For example:  I have 100+ torrents seeding right now (anime), but my SSD is full. I want to move them to another to have free space on the one i use for other stuff but im postponing this because of the work that will be, i will probably just delete the torrents and stop seeding :P
To use the script i would have to make the 100 torrents manually, since i have to get the hash myself so it would be good if i could like

script.py -syncall -p "D:"

-syncall : get all torrent hashes on qbittorrent
-p "D" : folder to look for the files to sync

**Comment by xob0t** [comment]
qBittorrent has that built in, you can select all the torrents you want to move, select "set location" option from the context menu, and it will move them all to the folder you specified
https://forum.qbittorrent.org/viewtopic.php?p=23485&sid=7172bf66cdebca61bb621f7aa70b6301#p23485

**Comment by x3vyx** [comment]
> qBittorrent has that built in, you can select all the torrents you want to move, select "set location" option from the context menu, and it will move them all to the folder you specified https://forum.qbittorrent.org/viewtopic.php?p=23485&sid=7172bf66cdebca61bb621f7aa70b6301#p23485

That it will not work. Will pick some torrents i have here for example:
Torrent 1 - "[Kirinashi] Undead Unluck - 007 [01ACD9C7].mkv"
Its just the file, placed on "...\Animes\Undead Unluck"

Torrent 2 - "Working!! 1-13 HDTV"
This actually was Folder - Working!!
                               Files - Ep 1...ep13
I tested the script moving around, works nice, now the torrent is:
Folder - Working!!
Folder - Season 01
Files - Ep 1...ep13

placed on "...\Animes"

Is like this because of the program i use to auto rename to work right with media system (jellyfin)

Torrent 3 - "[Infinite Fansub] Asobi Asobase [BD 1080p FLAC]"
Folder - Season 01
Files - Ep1...ep12

placed on "...\Animes\Asobi Asobase"

This one for example i rename the folder for season 01 because this torrent is just 1 folder before the files, and i need one folder before with the show name to the metadata providers work automatically.


Selecting all torrents, then set location for D: will result in a mess
Torrent 1 the file will just be on D:
Torrent 2 will be D:\Asobi Asobase
Torrent 3 files will be under D:\Season 01 (in that case, all batch torrents will be moved to here, so no go)

**Comment by x3vyx** [comment]
> qBittorrent has that built in, you can select all the torrents you want to move, select "set location" option from the context menu, and it will move them all to the folder you specified https://forum.qbittorrent.org/viewtopic.php?p=23485&sid=7172bf66cdebca61bb621f7aa70b6301#p23485

That it will not work. Will pick some torrents i have here for example:
Torrent 1 - "[Kirinashi] Undead Unluck - 007 [01ACD9C7].mkv"
Its just the file, placed on "...\Animes\Undead Unluck\Season 01"

Torrent 2 - "Working!! 1-13 HDTV"
This actually was Folder - Working!!
                               Files - Ep 1...ep13
I tested the script moving around, works nice, now the torrent is:
Folder - Working!!
Folder - Season 01
Files - Ep 1...ep13

placed on "...\Animes"

Is like this because of the program i use to auto rename to work right with media system (jellyfin)

Torrent 3 - "[Infinite Fansub] Asobi Asobase [BD 1080p FLAC]"
Folder - Season 01
Files - Ep1...ep12

placed on "...\Animes\Asobi Asobase"

This one for example i rename the folder for season 01 because this torrent is just 1 folder before the files, and i need one folder before with the show name to the metadata providers work automatically.


Selecting all torrents, then set location for D: will result in a mess
Torrent 1 the file will just be on D: and all torrents that is just the files will be placed like this too
Torrent 2 will be D:\Asobi Asobase
Torrent 3 files will be under D:\Season 01 (in that case, all batch torrents will be moved to here, so no go)

i just tested here, moved the Folder "Working!!" from "C:\Users\x3vyx\Secret\Animes" to C:\Users\x3vyx\Downloads"
move some files insde to the downloads folder, some to a new folder, let some in the same folder
run python qbittorrent_file_matcher.py a9c06c5a025f6b5c91bac3ec963309232e215e04 -d "C:\Users\x3vyx\Downloads"
and worked flawlessly

The thing that is missing it is to do this to all torrents with one command

**Comment by x3vyx** [comment]
Any way to instead of torrent hash use a .txt with the hashes?

**Comment by xob0t** [comment]
> Any way to instead of torrent hash use a .txt with the hashes?

done :)
test it out in the dev branch
https://github.com/xob0t/qBittorrent-File-Matcher/blob/dev/qbittorrent_file_matcher.py

**Comment by x3vyx** [comment]
Nice, it works. Also the command -s can be a patch above the download path, i just test it and works nice. Thank you very much @xob0t you saved me a lot of work or someone download, since some things im the only seeder xD

**Comment by x3vyx** [comment]
Hi @xob0t 

I use chatgpt to help me, now can use command -a to get all hashes and match, i dont have the knowledge to understand if the code is right, but its working for me.

i use this command, no error till now

```
python qbittorrent_file_matcher.py -a -s C:\Users\x3vyx\Secret\Animes -d C:\Users\x3vyx\Secret\Animes
pause
``` 

```python
import argparse
import configparser
import os
import sys
from pathlib import Path

try:
    from colorama import Fore, Style, init
    from InquirerPy import prompt
    from qbittorrentapi import Client
except ModuleNotFoundError:
    print("You need to install the dependencies.")
    print("If you have pip (normally installed with python), run this command in a terminal (cmd):")
    print('pip install colorama inquirerpy qbittorrent-api')
    sys.exit()

def get_config():
    default_config = {
        'Client': {
            'host': 'localhost:8080',
            'username': 'admin',
            'password': 'adminadmin'
        }
    }
    config_file = 'client.ini'
    
    config = configparser.ConfigParser()

    if not os.path.exists(config_file):
        print('client.ini not found')
        make_new_config(default_config, config, config_file)

    config.read(config_file)
    host = config.get('Client', 'host', fallback=default_config['Client']['host'])
    username = config.get('Client', 'username', fallback=default_config['Client']['username'])
    password = config.get('Client', 'password', fallback=default_config['Client']['password'])

    return host, username, password

def make_new_config(default_config, config, config_file):
    host = input(f"Enter qBittorrent Web UI host (Empty to use {default_config['Client']['host']}): ")
    host = host.strip() or default_config['Client']['host']
    print(f"Using qBittorrent Web UI host: {host}")

    username = input(f"Enter qBittorrent Web UI username (Empty to use {default_config['Client']['username']}): ")
    username = username.strip() or default_config['Client']['username']
    print(f"Using qBittorrent Web UI username: {username}")

    password = input(f"Enter qBittorrent Web UI password (Empty to use {default_config['Client']['password']}): ")
    password = password.strip() or default_config['Client']['password']
    print("Using qBittorrent Web UI password: *****")  # For security, we only print asterisks for the password

    # Save the new credentials to client.ini
    config['Client'] = {}
    config['Client']['host'] = host
    config['Client']['username'] = username
    config['Client']['password'] = password
    with open(config_file, 'w') as f:
        config.write(f)
    print("client.ini created")

def init_client():
    host, username, password = get_config()
    return Client(host=host, username=username, password=password)


def get_matching_files_in_dir_and_subdirs(search_path, sizes):
    files_in_directory = [os.path.join(dirpath, name) for dirpath, _, filenames in os.walk(search_path) for name in filenames]
    print(f"Found {len(files_in_directory)} files in the search directory")

    files_and_sizes = map(lambda file: [file, os.path.getsize(file)], files_in_directory)

    matched_files = [pair for pair in files_and_sizes if pair[1] in sizes]
    return matched_files

def match(torrent, files_in_directory, match_extension, download_path, is_dry_run):
    matched_files = set()  # keep track of already matched files
    for torrent_file in torrent.files:
        matching_files = []
        for disk_file_abs_path, disk_file_size in files_in_directory:
            if (torrent_file.size == disk_file_size and
                (not match_extension or Path(disk_file_abs_path).suffix == Path(torrent_file.name).suffix) and
                disk_file_abs_path not in matched_files):
                matching_files.append(disk_file_abs_path)

        if len(matching_files) > 1:
            question = [
                {
                    "type": "list",
                    "message": f"Multiple matches found for {torrent_file.name}. Select a file to match:",
                    "choices": matching_files,
                    "name": "file",
                }
            ]
            response = prompt(question)
            selected_file_path = response["file"]
        elif matching_files:
            selected_file_path = matching_files[0]
        else:
            print(f"{Fore.RED}No matches found for {torrent_file.name}!{Style.RESET_ALL}")
            continue

        matched_files.add(selected_file_path)
        new_relative_path = Path(selected_file_path).relative_to(download_path).as_posix()
        if new_relative_path == torrent_file.name:
            print(f"File:\n{torrent_file.name} left as is")
            continue
        if is_dry_run:
            print(f"{Fore.YELLOW}Dry run:{Style.RESET_ALL}\n{torrent_file.name} ->\n{Fore.YELLOW}{new_relative_path}{Style.RESET_ALL}")
            continue
        print(f"Renaming file:\n{torrent_file.name} ->\n{Fore.GREEN}{new_relative_path}{Style.RESET_ALL}")
        torrent.rename_file(file_id=torrent_file.id, new_file_name=new_relative_path)

def set_search_and_download_paths(torrent, input_search_path, input_download_path, use_torrent_save_path_as_search_path):
    content_path = torrent.content_path
    download_path = torrent.save_path
    search_path = ''

    if input_download_path:
        content_path = str(Path(input_download_path).joinpath(Path(content_path).relative_to(download_path)))
        download_path = input_download_path
    if input_search_path.startswith(str(Path(download_path).resolve())):
        search_path = input_search_path
    elif input_search_path and not input_search_path.startswith(str(Path(download_path).resolve())):
        sys.exit(f"Search path {input_search_path} must be sub directory of {download_path}")
    elif use_torrent_save_path_as_search_path or not Path(content_path).exists():
        search_path = download_path
    else:
        search_path = content_path

    search_path = search_path if Path(search_path).exists() else sys.exit(f"Search path {search_path} does not exist")
    download_path = download_path if Path(download_path).exists() else sys.exit(f"Download path {download_path} does not exist")

    return search_path, download_path


def main(torrent_hash, input_search_path=None, input_download_path=None, use_torrent_save_path_as_search_path=False, match_extension=False, is_dry_run=False):
    init() #colorama
    client = init_client()
    print("connected to api")
    torrents_info = client.torrents.info(torrent_hashes=torrent_hash)

    torrent = torrents_info[0] if torrents_info else sys.exit("No torrent found with the given hash")
    print(f"Target torrent: {torrent.name}")

    search_path , download_path = set_search_and_download_paths(torrent, input_search_path, input_download_path, use_torrent_save_path_as_search_path)
    print(f"Search directory {search_path}\nDownload directory {download_path}")
    torrent_file_sizes = set(file.size for file in torrent.files)
    files_in_directory = get_matching_files_in_dir_and_subdirs(search_path, torrent_file_sizes)
    print("Looking for matches")
    match(torrent, files_in_directory, match_extension, download_path, is_dry_run)
    if input_download_path and input_download_path != torrent.save_path and not is_dry_run:
        print(f"Changing torrent save location to {input_download_path}")
        client.torrents_set_location(torrent_hashes=torrent_hash, location=input_download_path)
        print(f"{Fore.LIGHTMAGENTA_EX}Rechecking torrent{Style.RESET_ALL}")
        client.torrents_recheck(torrent_hash)
    if is_dry_run:
        print(f"{Fore.YELLOW}Performed a dry run, nothing was modified{Style.RESET_ALL}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Tool to match torrents added to qBittorent to files on a disk")
    parser.add_argument('-a', '--all', action='store_true', help='Match all torrents.')
    parser.add_argument('-s', '-spath', default='', help="Specifies search path. Must be a subpath of the download path.")
    parser.add_argument('-d', '-dpath', default='', help="Sets new download path for the torrent.")
    parser.add_argument('-fd', action='store_true', help="Forces search in torrent's download directory. Default is torrent's content directory. Ignored if passed along with search.")
    parser.add_argument('-e', '-ext', action='store_true', help="Forces matched files to share an extension.")
    parser.add_argument('-dry', action='store_true', help="Performs a dry run without modifying anything.")

    args = parser.parse_args()

    if args.all:
        client = init_client()
        hashes = [torrent.hash for torrent in client.torrents_info()]
        for torrent_hash in hashes:
            main(torrent_hash, args.s, args.d, args.fd, args.e, args.dry)
    else:
        parser.add_argument('hash', help='Torrent hash, or a txt with a list of hashes.')
        args = parser.parse_args()

        if os.path.isfile(args.hash):
            with open(args.hash, "r") as file:
                hashes = file.read()
            for hash_ in hashes.split('\n'):
                main(hash_, args.s, args.d, args.fd, args.e, args.dry)
        else:
            main(args.hash, args.s, args.d, args.fd, args.e, args.dry)
```

**Comment by xob0t** [comment]
cool :D
i've added this option in the dev branch, and also fixed a couple of bugs.
If you can test it and confirm i did not broke anything in the process, that would be great.

**Comment by x3vyx** [comment]
tested, for the same thing I was doing couldnt find any bug

**Comment by nicpaesk** [comment]
Hello! I'm not finding a dev branch. Could this be added to the main one? It would be amazing. Cheers!

**Comment by xob0t** [comment]
@nicpaesk It's been merged into main

**Comment by nicpaesk** [comment]
Great! Sorry I looked for a documentation for the -a but I guess the readme is slightly behind. Thank you!!
