### ISSUE TITLE
[Other] Theme

### ISSUE THREAD

**Issue by x3vyx** [xob0t/qBittorrent-File-Matcher#3]
I really liked the theme of your qbit on the demo, its like the default one but dark, none of the themes that a find its like this
"https://raw.githubusercontent.com/xob0t/qBittorrent-File-Matcher/main/media/demo.webp"

Can you provide for us? xD

Thanks!

**Comment by xob0t** [comment]
https://github.com/jagannatharjun/qbt-theme#mumble-darkqbtheme
