### ISSUE TITLE
More than one qBittorrent instance

### ISSUE THREAD

**Issue by nicpaesk** [xob0t/qBittorrent-File-Matcher#8]
Hello,

I run two instances of qBittorrent in my pc: one for private trackers, and another for the same files on public trackers. I cannot use one for both as qBittorrent would merge them.

Would this work in this case? If not, is there a workaround? I don't know, maybe creating a docker image with just qBittorrent and this script?

All the best!

**Comment by xob0t** [comment]
Should not be a problem. Just make sure to use different ports for different qBittorent instances, or just don't run them simultaneously.
